INSERT INTO BASEBOARD (TITLE, CONTENT, WRITER, REGDATE)
VALUES ("첫번째 글", "첫번째 내용", "ADMIN", NOW())

INSERT INTO BASEBOARD (TITLE, CONTENT, WRITER, REGDATE)
VALUES ("두번째 글", "두번째 내용", "ADMIN", NOW())

USE board;

TRUNCATE BASEBOARD;

DROP TABLE BASEBOARD;


CREATE TABLE BASEBOARD
(
	IDX			INT				AUTO_INCREMENT	PRIMARY KEY		NOT NULL,
	NUM			INT				default 0,
	TITLE		VARCHAR(150)	NOT NULL,
	CONTENT		VARCHAR(8000)	NOT NULL,
	WRITER		VARCHAR(100)	NOT NULL,
	REGDATE		DATETIME		NOT NULL,
	MODDATE		DATETIME
);


SELECT * FROM BASEBOARD